# fly.toml app configuration file generated for back-founder-side-project on 2023-06-23T03:17:41+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "back-founder-side-project"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[deploy]
  release_command = "bin/rails db:prepare"

[processes]
  app = ""
  cron = "sh bin/cron"