---
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: 
  <<: *default
  database: back_founder_side_project_development

test:
  <<: *default
  database: back_founder_side_project_test

production:
  <<: *default
  database: back_founder_side_project_production
  host: "<%= ENV['DATABASE_HOST'] %>"
  username: "<%= ENV['DATABASE_USERNAME'] %>"
  password: "<%= ENV['DATABASE_PASSWORD'] %>"
  pool: 50