invalid_client:
  error_code: 400_001
  error_message: invalid client
invalid_email:
  error_code: 400_002
  error_message: invalid email
email_already_registered:
  error_code: 400_005
  error_message: email already registered
