invalid_client:
  error_code: 400_001
  error_message: invalid client
invalid_email:
  error_code: 400_002
  error_message: invalid email
email_already_registered:
  error_code: 400_005
  error_message: email already registered

post_not_found:
  error_code: 404_001
  error_message: post not found
comment_not_found:
  error_code: 404_002
  error_message: comment not found

comment_already_voted:
  error_code: 406_001
  error_message: user already voted the comment
